version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: suite_educativa_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: suite_educativa
    ports:
      - "3310:3306"
    volumes:
      - suite_educativa_mysql_data:/var/lib/mysql

volumes:
  suite_educativa_mysql_data: